apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  configManagementPlugins: |
    - name: solsa
      generate:
        command: [sh, -c]
        args: ["/solsa/solsa/node_modules/solsa/solsa yaml $SOLSA_APP_MAIN --config /solsa/solsa-config/solsa.yaml --cluster ${SOLSA_CLUSTER:-in-cluster} --context ${SOLSA_CONTEXT:-in-cluster-context} $SOLSA_EXTRA_ARGS"]
