name: Publish assets

on:
  release:
    types:
      - published

jobs:
  publish-assets:
    runs-on: ubuntu-latest

    env:
      DIST_DIR: ./dist
      PUBLISH_BRANCH: gh-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Install yq
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y

      - name: Build module.yaml
        run: |
          ./.github/scripts/build-module-metadata.sh ${{ github.event.release.tag_name }} ${{ env.DIST_DIR }} ${{ github.repository }}
          cp README.md ${{ env.DIST_DIR }}
          mkdir -p ./scripts && cp ./.github/scripts/merge-module-metadata.sh ./scripts

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.PUBLISH_BRANCH }}
          clean: false

      - name: Build index.yaml
        run: |
          ./scripts/merge-module-metadata.sh ${{ env.DIST_DIR }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.DIST_DIR }}
          publish_branch: ${{ env.PUBLISH_BRANCH }}