name: Publish metadata

on:
  release:
    types:
      - published

jobs:
  publish-assets:
    uses: cloud-native-toolkit/action-workflows/.github/workflows/publish-metadata.yaml@v1
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
